"""core_schema

Revision ID: 63851bd8742e
Revises: 49508d096eac
Create Date: 2026-03-08 09:32:27.274390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '63851bd8742e'
down_revision: Union[str, None] = '49508d096eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_report_year'), 'documents', ['report_year'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('canonical_metric_id', sa.String(length=64), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=True),
    sa.Column('metric_name', sa.String(length=256), nullable=False),
    sa.Column('metric_name_en', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=True),
    sa.Column('default_unit', sa.String(length=64), nullable=True),
    sa.Column('applicable_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_statement_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('canonical_metric_id')
    )
    op.create_index(op.f('ix_metric_definitions_metric_code'), 'metric_definitions', ['metric_code'], unique=True)
    op.create_table('validation_rules',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('applicable_metric_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_company_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_validation_rules_rule_code'), 'validation_rules', ['rule_code'], unique=True)
    op.create_table('canonical_tables',
    sa.Column('table_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('table_title_raw', sa.Text(), nullable=True),
    sa.Column('table_title_norm', sa.Text(), nullable=True),
    sa.Column('unit_raw', sa.String(length=64), nullable=True),
    sa.Column('currency_raw', sa.String(length=64), nullable=True),
    sa.Column('table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('parse_engine', sa.String(length=64), nullable=True),
    sa.Column('parse_confidence', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('parse_trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index(op.f('ix_canonical_tables_document_id'), 'canonical_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_canonical_tables_template_fingerprint'), 'canonical_tables', ['template_fingerprint'], unique=False)
    op.create_table('document_pages',
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('page_image_path', sa.Text(), nullable=True),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('metric_aliases',
    sa.Column('alias_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_metric_id', sa.String(length=64), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('alias_lang', sa.String(length=16), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('valid_from_year', sa.Integer(), nullable=True),
    sa.Column('valid_to_year', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_metric_id'], ['metric_definitions.canonical_metric_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_metric_aliases_alias_text'), 'metric_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_metric_aliases_canonical_metric_id'), 'metric_aliases', ['canonical_metric_id'], unique=False)
    op.create_index(op.f('ix_metric_aliases_company_id'), 'metric_aliases', ['company_id'], unique=False)
    op.create_table('facts',
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('statement_scope', sa.String(length=64), nullable=True),
    sa.Column('canonical_metric_id', sa.String(length=64), nullable=True),
    sa.Column('metric_name_std', sa.String(length=256), nullable=True),
    sa.Column('metric_alias_raw', sa.Text(), nullable=True),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('unit_raw', sa.String(length=64), nullable=True),
    sa.Column('unit_std', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_page_no', sa.Integer(), nullable=True),
    sa.Column('source_table_id', sa.String(length=64), nullable=True),
    sa.Column('source_row_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_col_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_cell_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_text_snippet', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('validation_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_metric_id'], ['metric_definitions.canonical_metric_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['canonical_tables.table_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_facts_canonical_metric_id'), 'facts', ['canonical_metric_id'], unique=False)
    op.create_index(op.f('ix_facts_company_id'), 'facts', ['company_id'], unique=False)
    op.create_index(op.f('ix_facts_document_id'), 'facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_facts_report_year'), 'facts', ['report_year'], unique=False)
    op.create_index(op.f('ix_facts_review_status'), 'facts', ['review_status'], unique=False)
    op.create_table('review_logs',
    sa.Column('review_log_id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.fact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_log_id')
    )
    op.create_index(op.f('ix_review_logs_fact_id'), 'review_logs', ['fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_fact_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_facts_review_status'), table_name='facts')
    op.drop_index(op.f('ix_facts_report_year'), table_name='facts')
    op.drop_index(op.f('ix_facts_document_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_company_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_canonical_metric_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_metric_aliases_company_id'), table_name='metric_aliases')
    op.drop_index(op.f('ix_metric_aliases_canonical_metric_id'), table_name='metric_aliases')
    op.drop_index(op.f('ix_metric_aliases_alias_text'), table_name='metric_aliases')
    op.drop_table('metric_aliases')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_canonical_tables_template_fingerprint'), table_name='canonical_tables')
    op.drop_index(op.f('ix_canonical_tables_document_id'), table_name='canonical_tables')
    op.drop_table('canonical_tables')
    op.drop_index(op.f('ix_validation_rules_rule_code'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_metric_definitions_metric_code'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_documents_report_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
